# Generated by Django 4.2.1 on 2023-06-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('body', models.TextField()),
                ('user', models.CharField(default='me', max_length=20)),
                ('mail', models.EmailField(default='kyw4846@gmail.com', max_length=30)),
            ],
        ),
    ]
