# Generated by Django 4.2.1 on 2023-06-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='email',
            field=models.EmailField(default='user.example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
