# Generated by Django 4.2.1 on 2023-06-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_blog_email_blog_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BLog',
            new_name='Post',
        ),
    ]
