# Generated by Django 4.2.1 on 2023-05-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='writer',
            field=models.CharField(default='Default Writer', max_length=20),
            preserve_default=False,
        ),
    ]
