# Generated by Django 4.2.1 on 2023-05-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud1app', '0002_blog_user_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='email',
            field=models.EmailField(default='', max_length=132),
        ),
    ]
