# Generated by Django 4.2.1 on 2023-06-01 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud1app', '0003_blog_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Post',
        ),
    ]
