# Generated by Django 4.2.1 on 2023-06-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud1app', '0004_rename_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(default='', max_length=20),
        ),
    ]
