# Generated by Django 4.2.1 on 2023-05-28 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud1app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(default=datetime.datetime(2023, 5, 28, 8, 59, 58, 798500, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
    ]
