# Generated by Django 4.2.1 on 2023-05-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud1app', '0003_remove_blog_name_blog_useremail_blog_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='useremail',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='userword',
        ),
        migrations.AddField(
            model_name='blog',
            name='boolean',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
