# Generated by Django 4.2.1 on 2023-05-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud2app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='useremail',
            field=models.EmailField(default='example@example.com', max_length=254, verbose_name='사용자 이메일'),
        ),
        migrations.AddField(
            model_name='blog',
            name='username',
            field=models.CharField(default='guest', max_length=20, verbose_name='사용자명'),
        ),
        migrations.AddField(
            model_name='blog',
            name='userword',
            field=models.CharField(default='default_password', max_length=64, verbose_name='비밀번호'),
        ),
    ]
