# Generated by Django 4.2.1 on 2023-06-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud2app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='data published')),
                ('body', models.TextField()),
                ('user', models.CharField(default=False, max_length=20)),
                ('student', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='BLog',
        ),
    ]
